# 🤖 Dataset in Machine Learning

## 📚 Introduction

> **datasets are the foundation of Machine learning**
A **dataset** is a collection of data used to **analyze information, find patterns, and train Machine Learning models**.

| 🔧 components | 📌 Purpose |
|:---|:---|
| 📊 **Features** | Input data used by the model | 
| 🎯 **Target** | Output value the model predicts | 
| 📝 **Rows** | Individual data samples | 
| 📋 **Columns** | Data attributes / variables |

---

## 🔗 ML Workflow

**📥 Data → ⚙️ Processing → 📊 Visualization → 🤖 ML Model**

**load modules**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display
from  sklearn.datasets import load_iris

In [15]:
iris_dataset = load_iris()
print("Keys of iris_dataset:\n")
# print("keys of iris_dataset:\n{}\n".format(iris_dataset.keys())) instead of this i like to use for loop to print the keys of iris_dataset
for key in iris_dataset.keys():
    print(key,end="  ")

Keys of iris_dataset:

data  target  frame  target_names  DESCR  feature_names  filename  data_module  

**explore keys**

In [ ]:
print("\nData:\n{}".format(iris_dataset['data'][:5])) # first five rows of data


Data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [17]:
print("\nTarget names:\n{}".format(iris_dataset['target_names']))


Target names:
['setosa' 'versicolor' 'virginica']


In [22]:
print("\ntarget:\n{}".format(iris_dataset['target'])) # first five target values


target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [23]:
print("\nfeature names:\n{}".format(iris_dataset['feature_names'])  )


feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [27]:
print("\ndescription:\n{}".format(iris_dataset['DESCR'][:193] + "\n...")) # first five target values


description:
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...
